# -*- coding: utf-8 -*-
"""tif_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRFXAEkbLcuFVR0DCYd3epLzo36jAXLh
"""

#!pip install rasterio numpy

import rasterio
import numpy as np

def get_raster_value(raster_path, latitude, longitude):
    with rasterio.open(raster_path) as dataset:
        transform = dataset.transform

        # Convert (longitude, latitude) to (col, row)
        col, row = ~transform * (longitude, latitude)
        row, col = int(row), int(col)

        band_data = dataset.read(1)

        if 0 <= row < band_data.shape[0] and 0 <= col < band_data.shape[1]:
            return band_data[row, col]
        else:
            return None  # Coordinate out of bounds

# Example usage
raster_path = '/home/yashna/Desktop/btp/sm_tif/sm_surface_analysis_georeferenced_2017_01_01.tif'  # Replace with actual file name
latitude = float(input("Enter latitude: "))
longitude = float(input("Enter longitude: "))

value = get_raster_value(raster_path, latitude, longitude)
print(f"Value at latitude {latitude}, longitude {longitude}: {value/255}")

