version: '3'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/amd64}
    image: ${DOCKER_USERNAME}/ahrc-api:latest
    container_name: ahrc-api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_ENV=production

  # Next.js Frontend Service with pnpm
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/amd64}
    image: ${DOCKER_USERNAME}/ahrc-ui:latest
    container_name: ahrc-ui
    ports:
      - "3000:3000"
    environment:
      # Use the backend service name to connect from within Docker
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped