version: '3'
services:
  # Irrigation Backend Service
  irrigation-backend:
    build:
      context: ./backend/irrigation
      dockerfile: Dockerfile
    container_name: ahrc-irrigation-api
    ports:
      - "8000:8000"
    volumes:
      - ./logs/irrigation:/app/logs
      - ./data/irrigation:/app/data
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_ENV=production
    networks:
      - ahrc-network

  # Cancer Detection Backend Service
  cervic-backend:
    build:
      context: ./backend/cervic_cancer
      dockerfile: Dockerfile
    container_name: ahrc-cervic-cancer-api
    ports:
      - "8001:8001"
    volumes:
      - ./logs/cancer:/app/logs
      - ./data/cancer:/app/data
      - ./models:/app/models
      - ./predictions:/app/predictions
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_ENV=production
    networks:
      - ahrc-network

  # Chemotherapy Toxicity Prediction Backend Service
  chemo-backend:
    build:
      context: ./backend/chemo
      dockerfile: Dockerfile
    container_name: ahrc-chemo-api
    ports:
      - "8002:8002"
    volumes:
      - ./logs/chemo:/app/logs
      - ./data/chemo:/app/data
      - ./models/chemo:/app/models
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_ENV=production
    networks:
      - ahrc-network

  # OCT Segmentation Backend Service
  oct-backend:
    build:
      context: ./backend/oct
      dockerfile: Dockerfile
    container_name: ahrc-oct-api
    ports:
      - "8004:8004"
    volumes:
      - ./logs/oct:/app/logs
      - ./data/oct:/app/data
      - ./models/oct:/app/models
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - API_ENV=production
    networks:
      - ahrc-network

  # Next.js Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ahrc-ui
    ports:
      - "3000:3000"
    environment:
      # Multiple API URLs for different services
      - NEXT_PUBLIC_IRRIGATION_API_URL=http://irrigation-backend:8000
      - NEXT_PUBLIC_CERVIC_API_URL=http://cervic-backend:8001
      - NEXT_PUBLIC_CHEMO_API_URL=http://chemo-backend:8002
      - NEXT_PUBLIC_OCT_API_URL=http://oct-backend:8004
    depends_on:
      - irrigation-backend
      - cervic-backend
      - chemo-backend
      - oct-backend
    restart: unless-stopped
    networks:
      - ahrc-network

networks:
  ahrc-network:
    driver: bridge